model_path: "stabilityai/stablelm-base-alpha-3b"
tokenizer_path: "stabilityai/stablelm-base-alpha-3b"
# model_path: "facebook/opt-30b" 
# tokenizer_path: "facebook/opt-30b"
save_dir: "../ckpts/bpt-instruct"

train_args:
  output_dir: "../ckpts/bpt-instruct"
  num_train_epochs: 3
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 2.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True
  evaluation_strategy: "epoch"


# data_path: "Dahoas/sft-synthetic-hh"
data_path: "nomic-ai/gpt4all-j-prompt-generations"
# data_path: "Dahoas/sft-hh-rlhf"

