model_path: "EleutherAI/gpt-j-6B"
tokenizer_path: "EleutherAI/gpt-j-6B"
# model_path: "facebook/opt-30b" 
# tokenizer_path: "facebook/opt-30b"
save_dir: "../ckpts/bpt-sft"

train_args:
  output_dir: "../ckpts/bpt-sft"
  num_train_epochs: 16
  logging_steps: 500
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 9.65e-6
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True
  evaluation_strategy: "epoch"


data_path: "Dahoas/pythia_synthetic_20B_inference_train"
# data_path: "robertmyers/bpt-static"
# data_path: "Dahoas/sft-hh-rlhf"

