model_path: "facebook/opt-13b"
tokenizer_path: "facebook/opt-13b"
save_dir: "../ckpts/bt-opt-sft"

train_args:
  output_dir: "../ckpts/bt-opt-sft"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 3.0e-4
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True
  evaluation_strategy: "epoch"

data_path: "Dahoas/sft-static"