model_path: "gpt2"
tokenizer_path: "gpt2"
save_dir: "../ckpts/gpt2-sft"

train_args:
  output_dir: "../ckpts/gpt2-sft"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-4
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: True
  bf16: False
  evaluation_strategy: "epoch"

data_path: "Dahoas/sft-static"