model_path: "EleutherAI/gpt-neo-1.3B"
tokenizer_path: "EleutherAI/gpt-neo-1.3B"
save_dir: "../ckpts/gptneo-sft"

train_args:
  output_dir: "../ckpts/gptneo-sft"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 3
  per_device_eval_batch_size: 3
  warmup_steps: 100
  weight_decay: 0.01
  save_total_limit: 1
  learning_rate: 1.0e-4
  logging_dir: "./logs"
  fp16: True
  bf16: False
  evaluation_strategy: "epoch"

data_path: "Dahoas/sft-static"